# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "11.x"
    displayName: "Install Node.js"

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: "Use Yarn 1.x"

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName:
      "Yarn (install dependencies)"
      # - script: |
  #     npm install
  #     npm run build
  #   displayName: "npm install and build"
# - task: Npm@1
#   displayName: 'npm install'
#   inputs:
#     command: install

# - task: Npm@1
#   displayName: 'npm test'
#   inputs:
#     command: custom
#     customCommand: 'test'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFiles: '**/TEST-RESULTS.xml'
#     testRunTitle: 'Test results for JavaScript'
#   condition: succeededOrFailed()

# - task: PublishCodeCoverageResults@1
#   inputs:
#     codeCoverageTool: Cobertura
#     summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
#     reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
#     includeRootFolder: false

# - task: PublishBuildArtifacts@1
